Repository lutzzdias/travelling-salesman-problem, pull requests merged in 2023-11, with the labels that each got.

#23 #11: add_moves
  .gitignore
  README.md
  travelling_salesman.py
Labels: solution, component

#27 #4 [Component] constructor
  travelling_salesman.py
Labels: component

#29 20-Implemented lower_bound_incr_add
  travelling_salesman.py
Labels: solution

#28 #24 Simplify calculation of initial lower bound
  travelling_salesman.py
Labels: problem

#32 Greedy Solver
  solvers.py
  travelling_salesman.py
Labels: solver
